### ISSUE TITLE
Cannot get the has instance method in the simple inventory system to work 

### ISSUE THREAD

**Issue by Wassum0** [ChapelR/custom-macros-for-sugarcube-2#60]
I can't seem to get the has method to work. I'm using twine 2 and have the latest sugarcube 2.36.1 downloaded

I get this error method with the code below,

Error: <<if>>: bad conditional expression in <<if>> clause: Cannot read properties of undefined (reading 'has')
<<if $proffession.has('Student')>>     Is a student. <<else>>     Is not a student. <</if>>

the same thing occurs for the hasAll method.

Thanks for your work!

**Comment by ChapelR** [comment]
I just went and tested the simple inventory in the latest version of Twine and SugarCube and it appears to work fine for me. I suggest checking your spelling. Also, I can't really see what code you have posted there, GitHub's markdown ate up most of it. Try placing it between three grave marks.

&grave;&grave;&grave;
With three grave marks above and below...
&grave;&grave;&grave;

```
Content will render like this.
```

Otherwise a lot of SugarCube markup and macro code just becomes invisible.

If you are unable to solve the issue, just show as much code as you can, like where you set up the inventory, where you add stuff to it, and where the `has()` error is.

**Comment by Wassum0** [comment]
Sorry it was my spelling lol. Very mad I didnt realize this myself after troubleshooting for 2 hours last night. Apologies, but thank you so much for your help.

**Comment by ChapelR** [comment]
No worries, glad it's working now.
