### ISSUE TITLE
Speechbox with variables / conversation macro feature request

### ISSUE THREAD

**Issue by Amathele** [ChapelR/custom-macros-for-sugarcube-2#64]
Hi, it's me - again. Luckily i did not break anything this time around ;)

I have a question about the Say Macro.

is it possible to alter the displayed picture for a given character by variable? like so: `<<character 'You' 'images/speechbox/' + $someVar + '.jpg'>>`

second question regarding this, i have read you can have a displayname, so that the macro name stays the same - is this displayname also possible to be variabled?

`<<character 'You' '$name' 'picture.jpg'>>` ?

Thirdly I have a feature request - add a 'conversation' macro, where the picture of the speaker changes from left to right - or add a optional parameter to make the image in the say-macro be displayed left or right
`<<lisa flip>>` or `<<lisa right>>` for image display on right, maybe?

**Comment by ChapelR** [comment]
> is it possible to alter the displayed picture for a given character by variable? like so: `<<character 'You' 'images/speechbox/' + $someVar + '.jpg'>>`

This is what the `<<say>>` macro is for, which you can use to create widget if you want to. Nothing dynamic should be used in the `<<character>>` macro. 

I've actually considered removing the entire macro "factory" concept from this system in the future because I feel like it confuses people in exactly this way: people seem to feel like they're doing something wrong if they end up having to use the `<<say>>` macro instead of a custom one. With non-void widgets now being a thing in SugarCube anyway, the macro factory isn't really useful anymore.

In short, use `<<say>>` for when you need dynamic names or image paths (or just use `<<say>>` period, and make your own non-void widgets).

> second question regarding this, i have read you can have a displayname, so that the macro name stays the same - is this displayname also possible to be variabled?

This actually *should* work if you pass the variable as part of a string due to "naked variable markup," so try it out, I think it should actually work, but only really for display names. It won't really work with image paths or the identifier.

> Thirdly I have a feature request - add a 'conversation' macro, where the picture of the speaker changes from left to right - or add a optional parameter to make the image in the say-macro be displayed left or right
<<lisa flip>> or <<lisa right>> for image display on right, maybe?

This can probably handle this via CSS in most cases, like:

```css
.say:nth-of-type(even) img {
  float: right;
  margin-right: 0;
  margin-left: 1em;
}
```

But I'll consider making some kind of argument for this so users can have finer control.

**Comment by Amathele** [comment]
or make that css an optional thing in the say.css.

so you recommend just to use `<<say>>` instead of the `<<character>>`, got it.

**Comment by greyelf** [comment]
@Amathele 
If you, or anyone else reading this issue, are uncertain what is meant by the following...

> ...and make your own non-void widgets

It means that you can use SugarCubes own [`<<widget>>`](http://www.motoslave.net/sugarcube/2/docs/#macros-macro-widget) macro to pre-define a "character", instead of using the Speachbox's `<<character>>` macro.

eg. If you want to define a character who's identifier is **jane** then place code like the following within your project's [widget](http://www.motoslave.net/sugarcube/2/docs/#special-tag-widget) tagged Passage...
```
<<widget "jane" container>>
	<<say 'Jane' 'media/jana-face.png'>>_contents<</say>>
<</widget>>
```
..and then call the new `<<jane>>` widget within a Passage...
```
<<jane>>Hello, my name is Jane<</jane>>
```

And if you want the image path to be determined using a variable then you can do so within the `<<widget>>` you create...
```
<<widget "you" container>>
	<<say 'You' `"images/speechbox/" + $someVar + ".jpg"`>>_contents<</say>>
<</widget>>
```
Note: Read the **Argument type macros: passing an expression as an argument** section of the [Macro Arguments](http://www.motoslave.net/sugarcube/2/docs/#macros-arguments) documentation to learn why the above image path argument is wrapped in back-quote characters.

**Comment by Amathele** [comment]
thank you @greyelf
