### ISSUE TITLE
Console errors SugarCube 2.37.3

### ISSUE THREAD

**Issue by manonamora** [ChapelR/custom-macros-for-sugarcube-2#72]
Not really bugs, since the macros are still working, but still wanted to raise those
![image](https://github.com/user-attachments/assets/a609cc4f-a8ef-4f3f-9ee1-e0d578d24428)
Appearing when using the Fade-in/out Macro set
![image](https://github.com/user-attachments/assets/9d825a41-de91-444c-99d1-3b8ae13e6a56)
Appearing when using the Event Macro set

**Comment by ChapelR** [comment]
SugarCube 2.37 went on a bit of a spree of deprecating stuff. Some of the deprecation are just name changes too. The issue is that if I update the macro collection to remove all the deprecated functions and methods, many of the macros will no longer work in 2.36 and older. Maintaining two separate versions is not something I want to do, so I don't plan to take any action until SC actually makes these changes breaking.
